version: "2"

build:
  os: "ubuntu-lts-latest"
  apt_packages: 
    - libmagic1
    - cmake
    - ninja-build
  tools:
    python: "3.10"
  jobs:
    install:
      - |
        export CMAKE_ARGS="-Wno-dev -DCMAKE_POLICY_DEFAULT_CMP0169=OLD -DMEMILIO_ENABLE_WARNINGS_AS_ERRORS=OFF -DMEMILIO_BUILD_TESTS=OFF -DMEMILIO_BUILD_EXAMPLES=OFF -DMEMILIO_BUILD_BENCHMARKS=OFF -DMEMILIO_BUILD_SBML_MODELS=OFF -DMEMILIO_BUILD_STATIC_LIBS=OFF"
        pip install --exists-action=w --no-cache-dir -r docs/requirements-build.txt
        pip install --exists-action=w --no-cache-dir -r docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
