version: "2"

build:
  os: "ubuntu-lts-latest"
  apt_packages: 
    - libmagic1
    - cmake
    - ninja-build
  tools:
    python: "3.10"
  environment:
    CMAKE_ARGS: >-
      -Wno-dev
      -DCMAKE_POLICY_DEFAULT_CMP0169=OLD
      -DMEMILIO_ENABLE_WARNINGS_AS_ERRORS=OFF
  jobs:
    install:
      - pip install --exists-action=w --no-cache-dir -r docs/requirements-build.txt
      - pip install --exists-action=w --no-cache-dir -r docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
