name: "Windows Examples"
description: "Run the C++ examples on Windows"
inputs:
  build-artifact:
    description: "Name of the build artifact that contains the example binary."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download built example directory
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}
        path: cpp/build-win/bin
    - name: Run examples
      shell: pwsh
      run: |
        cd cpp/build-win/bin
        $errchk = (Get-ChildItem -Path ./| Where-Object { $_.Name -like "*_example.exe"} | Measure-Object).Count
        if( $errchk -gt 0){
          Write-Output "Running windows Examples."
          Get-ChildItem -Path ./| Where-Object { $_.Name -like "*_example.exe" } | ForEach-Object {
            Write-Output "Running $($_.Name)"
            & $_.FullName
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Programm terminated with error, aborting."
              Exit 1
            }
          }
        }
        else {
          Write-Output "No Examples found, abort."
          Exit 1
        }
