const Regions = {
  GERMANY: {dataset: 'germany', id: -1, label: 'Germany'},
  STATES: [
    {id: 1, dataset: 'states', label: 'Schleswig-Holstein'},
    {id: 2, dataset: 'states', label: 'Hamburg'},
    {id: 3, dataset: 'states', label: 'Niedersachsen'},
    {id: 4, dataset: 'states', label: 'Bremen'},
    {id: 5, dataset: 'states', label: 'Nordrhein-Westfalen'},
    {id: 6, dataset: 'states', label: 'Hessen'},
    {id: 7, dataset: 'states', label: 'Rheinland-Pfalz'},
    {id: 8, dataset: 'states', label: 'Baden-Württemberg'},
    {id: 9, dataset: 'states', label: 'Bayern'},
    {id: 10, dataset: 'states', label: 'Saarland'},
    {id: 11, dataset: 'states', label: 'Berlin'},
    {id: 12, dataset: 'states', label: 'Brandenburg'},
    {id: 13, dataset: 'states', label: 'Mecklenburg-Vorpommern'},
    {id: 14, dataset: 'states', label: 'Sachsen'},
    {id: 15, dataset: 'states', label: 'Sachsen-Anhalt'},
    {id: 16, dataset: 'states', label: 'Thüringen'},
  ],
  // AUTO GENERATED
  COUNTIES: [
    {label: 'Flensburg', dataset: 'counties', id: 1001},
    {label: 'Kiel', dataset: 'counties', id: 1002},
    {label: 'Lübeck', dataset: 'counties', id: 1003},
    {label: 'Neumünster', dataset: 'counties', id: 1004},
    {label: 'Dithmarschen', dataset: 'counties', id: 1051},
    {label: 'Herzogtum Lauenburg', dataset: 'counties', id: 1053},
    {label: 'Nordfriesland', dataset: 'counties', id: 1054},
    {label: 'Ostholstein', dataset: 'counties', id: 1055},
    {label: 'Pinneberg', dataset: 'counties', id: 1056},
    {label: 'Plön', dataset: 'counties', id: 1057},
    {label: 'Rendsburg-Eckernförde', dataset: 'counties', id: 1058},
    {label: 'Schleswig-Flensburg', dataset: 'counties', id: 1059},
    {label: 'Segeberg', dataset: 'counties', id: 1060},
    {label: 'Steinburg', dataset: 'counties', id: 1061},
    {label: 'Stormarn', dataset: 'counties', id: 1062},
    {label: 'Hamburg', dataset: 'counties', id: 2000},
    {label: 'Braunschweig', dataset: 'counties', id: 3101},
    {label: 'Salzgitter', dataset: 'counties', id: 3102},
    {label: 'Wolfsburg', dataset: 'counties', id: 3103},
    {label: 'Gifhorn', dataset: 'counties', id: 3151},
    {label: 'Goslar', dataset: 'counties', id: 3153},
    {label: 'Helmstedt', dataset: 'counties', id: 3154},
    {label: 'Northeim', dataset: 'counties', id: 3155},
    {label: 'Peine', dataset: 'counties', id: 3157},
    {label: 'Wolfenbüttel', dataset: 'counties', id: 3158},
    {label: 'Göttingen', dataset: 'counties', id: 3159},
    {label: 'Region Hannover', dataset: 'counties', id: 3241},
    {label: 'Diepholz', dataset: 'counties', id: 3251},
    {label: 'Hameln-Pyrmont', dataset: 'counties', id: 3252},
    {label: 'Hildesheim', dataset: 'counties', id: 3254},
    {label: 'Holzminden', dataset: 'counties', id: 3255},
    {label: 'Nienburg (Weser)', dataset: 'counties', id: 3256},
    {label: 'Schaumburg', dataset: 'counties', id: 3257},
    {label: 'Celle', dataset: 'counties', id: 3351},
    {label: 'Cuxhaven', dataset: 'counties', id: 3352},
    {label: 'Harburg', dataset: 'counties', id: 3353},
    {label: 'Lüchow-Dannenberg', dataset: 'counties', id: 3354},
    {label: 'Lüneburg', dataset: 'counties', id: 3355},
    {label: 'Osterholz', dataset: 'counties', id: 3356},
    {label: 'Rotenburg (Wümme)', dataset: 'counties', id: 3357},
    {label: 'Heidekreis', dataset: 'counties', id: 3358},
    {label: 'Stade', dataset: 'counties', id: 3359},
    {label: 'Uelzen', dataset: 'counties', id: 3360},
    {label: 'Verden', dataset: 'counties', id: 3361},
    {label: 'Delmenhorst', dataset: 'counties', id: 3401},
    {label: 'Emden', dataset: 'counties', id: 3402},
    {label: 'Oldenburg (Oldb)', dataset: 'counties', id: 3403},
    {label: 'Osnabrück', dataset: 'counties', id: 3404},
    {label: 'Wilhelmshaven', dataset: 'counties', id: 3405},
    {label: 'Ammerland', dataset: 'counties', id: 3451},
    {label: 'Aurich', dataset: 'counties', id: 3452},
    {label: 'Cloppenburg', dataset: 'counties', id: 3453},
    {label: 'Emsland', dataset: 'counties', id: 3454},
    {label: 'Friesland', dataset: 'counties', id: 3455},
    {label: 'Grafschaft Bentheim', dataset: 'counties', id: 3456},
    {label: 'Leer', dataset: 'counties', id: 3457},
    {label: 'Oldenburg', dataset: 'counties', id: 3458},
    {label: 'Osnabrück', dataset: 'counties', id: 3459},
    {label: 'Vechta', dataset: 'counties', id: 3460},
    {label: 'Wesermarsch', dataset: 'counties', id: 3461},
    {label: 'Wittmund', dataset: 'counties', id: 3462},
    {label: 'Bremen', dataset: 'counties', id: 4011},
    {label: 'Bremerhaven', dataset: 'counties', id: 4012},
    {label: 'Düsseldorf', dataset: 'counties', id: 5111},
    {label: 'Duisburg', dataset: 'counties', id: 5112},
    {label: 'Essen', dataset: 'counties', id: 5113},
    {label: 'Krefeld', dataset: 'counties', id: 5114},
    {label: 'Mönchengladbach', dataset: 'counties', id: 5116},
    {label: 'Mülheim an der Ruhr', dataset: 'counties', id: 5117},
    {label: 'Oberhausen', dataset: 'counties', id: 5119},
    {label: 'Remscheid', dataset: 'counties', id: 5120},
    {label: 'Solingen', dataset: 'counties', id: 5122},
    {label: 'Wuppertal', dataset: 'counties', id: 5124},
    {label: 'Kleve', dataset: 'counties', id: 5154},
    {label: 'Mettmann', dataset: 'counties', id: 5158},
    {label: 'Rhein-Kreis Neuss', dataset: 'counties', id: 5162},
    {label: 'Viersen', dataset: 'counties', id: 5166},
    {label: 'Wesel', dataset: 'counties', id: 5170},
    {label: 'Bonn', dataset: 'counties', id: 5314},
    {label: 'Köln', dataset: 'counties', id: 5315},
    {label: 'Leverkusen', dataset: 'counties', id: 5316},
    {label: 'Städteregion Aachen', dataset: 'counties', id: 5334},
    {label: 'Düren', dataset: 'counties', id: 5358},
    {label: 'Rhein-Erft-Kreis', dataset: 'counties', id: 5362},
    {label: 'Euskirchen', dataset: 'counties', id: 5366},
    {label: 'Heinsberg', dataset: 'counties', id: 5370},
    {label: 'Oberbergischer Kreis', dataset: 'counties', id: 5374},
    {label: 'Rheinisch-Bergischer Kreis', dataset: 'counties', id: 5378},
    {label: 'Rhein-Sieg-Kreis', dataset: 'counties', id: 5382},
    {label: 'Bottrop', dataset: 'counties', id: 5512},
    {label: 'Gelsenkirchen', dataset: 'counties', id: 5513},
    {label: 'Münster', dataset: 'counties', id: 5515},
    {label: 'Borken', dataset: 'counties', id: 5554},
    {label: 'Coesfeld', dataset: 'counties', id: 5558},
    {label: 'Recklinghausen', dataset: 'counties', id: 5562},
    {label: 'Steinfurt', dataset: 'counties', id: 5566},
    {label: 'Warendorf', dataset: 'counties', id: 5570},
    {label: 'Bielefeld', dataset: 'counties', id: 5711},
    {label: 'Gütersloh', dataset: 'counties', id: 5754},
    {label: 'Herford', dataset: 'counties', id: 5758},
    {label: 'Höxter', dataset: 'counties', id: 5762},
    {label: 'Lippe', dataset: 'counties', id: 5766},
    {label: 'Minden-Lübbecke', dataset: 'counties', id: 5770},
    {label: 'Paderborn', dataset: 'counties', id: 5774},
    {label: 'Bochum', dataset: 'counties', id: 5911},
    {label: 'Dortmund', dataset: 'counties', id: 5913},
    {label: 'Hagen', dataset: 'counties', id: 5914},
    {label: 'Hamm', dataset: 'counties', id: 5915},
    {label: 'Herne', dataset: 'counties', id: 5916},
    {label: 'Ennepe-Ruhr-Kreis', dataset: 'counties', id: 5954},
    {label: 'Hochsauerlandkreis', dataset: 'counties', id: 5958},
    {label: 'Märkischer Kreis', dataset: 'counties', id: 5962},
    {label: 'Olpe', dataset: 'counties', id: 5966},
    {label: 'Siegen-Wittgenstein', dataset: 'counties', id: 5970},
    {label: 'Soest', dataset: 'counties', id: 5974},
    {label: 'Unna', dataset: 'counties', id: 5978},
    {label: 'Darmstadt', dataset: 'counties', id: 6411},
    {label: 'Frankfurt am Main', dataset: 'counties', id: 6412},
    {label: 'Offenbach am Main', dataset: 'counties', id: 6413},
    {label: 'Wiesbaden', dataset: 'counties', id: 6414},
    {label: 'Bergstraße', dataset: 'counties', id: 6431},
    {label: 'Darmstadt-Dieburg', dataset: 'counties', id: 6432},
    {label: 'Groß-Gerau', dataset: 'counties', id: 6433},
    {label: 'Hochtaunuskreis', dataset: 'counties', id: 6434},
    {label: 'Main-Kinzig-Kreis', dataset: 'counties', id: 6435},
    {label: 'Main-Taunus-Kreis', dataset: 'counties', id: 6436},
    {label: 'Odenwaldkreis', dataset: 'counties', id: 6437},
    {label: 'Offenbach', dataset: 'counties', id: 6438},
    {label: 'Rheingau-Taunus-Kreis', dataset: 'counties', id: 6439},
    {label: 'Wetteraukreis', dataset: 'counties', id: 6440},
    {label: 'Gießen', dataset: 'counties', id: 6531},
    {label: 'Lahn-Dill-Kreis', dataset: 'counties', id: 6532},
    {label: 'Limburg-Weilburg', dataset: 'counties', id: 6533},
    {label: 'Marburg-Biedenkopf', dataset: 'counties', id: 6534},
    {label: 'Vogelsbergkreis', dataset: 'counties', id: 6535},
    {label: 'Kassel', dataset: 'counties', id: 6611},
    {label: 'Fulda', dataset: 'counties', id: 6631},
    {label: 'Hersfeld-Rotenburg', dataset: 'counties', id: 6632},
    {label: 'Kassel', dataset: 'counties', id: 6633},
    {label: 'Schwalm-Eder-Kreis', dataset: 'counties', id: 6634},
    {label: 'Waldeck-Frankenberg', dataset: 'counties', id: 6635},
    {label: 'Werra-Meißner-Kreis', dataset: 'counties', id: 6636},
    {label: 'Koblenz', dataset: 'counties', id: 7111},
    {label: 'Ahrweiler', dataset: 'counties', id: 7131},
    {label: 'Altenkirchen (Westerwald)', dataset: 'counties', id: 7132},
    {label: 'Bad Kreuznach', dataset: 'counties', id: 7133},
    {label: 'Birkenfeld', dataset: 'counties', id: 7134},
    {label: 'Cochem-Zell', dataset: 'counties', id: 7135},
    {label: 'Mayen-Koblenz', dataset: 'counties', id: 7137},
    {label: 'Neuwied', dataset: 'counties', id: 7138},
    {label: 'Rhein-Hunsrück-Kreis', dataset: 'counties', id: 7140},
    {label: 'Rhein-Lahn-Kreis', dataset: 'counties', id: 7141},
    {label: 'Westerwaldkreis', dataset: 'counties', id: 7143},
    {label: 'Trier', dataset: 'counties', id: 7211},
    {label: 'Bernkastel-Wittlich', dataset: 'counties', id: 7231},
    {label: 'Eifelkreis Bitburg-Prüm', dataset: 'counties', id: 7232},
    {label: 'Vulkaneifel', dataset: 'counties', id: 7233},
    {label: 'Trier-Saarburg', dataset: 'counties', id: 7235},
    {label: 'Frankenthal (Pfalz)', dataset: 'counties', id: 7311},
    {label: 'Kaiserslautern', dataset: 'counties', id: 7312},
    {label: 'Landau in der Pfalz', dataset: 'counties', id: 7313},
    {label: 'Ludwigshafen am Rhein', dataset: 'counties', id: 7314},
    {label: 'Mainz', dataset: 'counties', id: 7315},
    {label: 'Neustadt an der Weinstraße', dataset: 'counties', id: 7316},
    {label: 'Pirmasens', dataset: 'counties', id: 7317},
    {label: 'Speyer', dataset: 'counties', id: 7318},
    {label: 'Worms', dataset: 'counties', id: 7319},
    {label: 'Zweibrücken', dataset: 'counties', id: 7320},
    {label: 'Alzey-Worms', dataset: 'counties', id: 7331},
    {label: 'Bad Dürkheim', dataset: 'counties', id: 7332},
    {label: 'Donnersbergkreis', dataset: 'counties', id: 7333},
    {label: 'Germersheim', dataset: 'counties', id: 7334},
    {label: 'Kaiserslautern', dataset: 'counties', id: 7335},
    {label: 'Kusel', dataset: 'counties', id: 7336},
    {label: 'Südliche Weinstraße', dataset: 'counties', id: 7337},
    {label: 'Rhein-Pfalz-Kreis', dataset: 'counties', id: 7338},
    {label: 'Mainz-Bingen', dataset: 'counties', id: 7339},
    {label: 'Südwestpfalz', dataset: 'counties', id: 7340},
    {label: 'Stuttgart', dataset: 'counties', id: 8111},
    {label: 'Böblingen', dataset: 'counties', id: 8115},
    {label: 'Esslingen', dataset: 'counties', id: 8116},
    {label: 'Göppingen', dataset: 'counties', id: 8117},
    {label: 'Ludwigsburg', dataset: 'counties', id: 8118},
    {label: 'Rems-Murr-Kreis', dataset: 'counties', id: 8119},
    {label: 'Heilbronn', dataset: 'counties', id: 8121},
    {label: 'Heilbronn', dataset: 'counties', id: 8125},
    {label: 'Hohenlohekreis', dataset: 'counties', id: 8126},
    {label: 'Schwäbisch Hall', dataset: 'counties', id: 8127},
    {label: 'Main-Tauber-Kreis', dataset: 'counties', id: 8128},
    {label: 'Heidenheim', dataset: 'counties', id: 8135},
    {label: 'Ostalbkreis', dataset: 'counties', id: 8136},
    {label: 'Baden-Baden', dataset: 'counties', id: 8211},
    {label: 'Karlsruhe', dataset: 'counties', id: 8212},
    {label: 'Karlsruhe', dataset: 'counties', id: 8215},
    {label: 'Rastatt', dataset: 'counties', id: 8216},
    {label: 'Heidelberg', dataset: 'counties', id: 8221},
    {label: 'Mannheim', dataset: 'counties', id: 8222},
    {label: 'Neckar-Odenwald-Kreis', dataset: 'counties', id: 8225},
    {label: 'Rhein-Neckar-Kreis', dataset: 'counties', id: 8226},
    {label: 'Pforzheim', dataset: 'counties', id: 8231},
    {label: 'Calw', dataset: 'counties', id: 8235},
    {label: 'Enzkreis', dataset: 'counties', id: 8236},
    {label: 'Freudenstadt', dataset: 'counties', id: 8237},
    {label: 'Freiburg im Breisgau', dataset: 'counties', id: 8311},
    {label: 'Breisgau-Hochschwarzwald', dataset: 'counties', id: 8315},
    {label: 'Emmendingen', dataset: 'counties', id: 8316},
    {label: 'Ortenaukreis', dataset: 'counties', id: 8317},
    {label: 'Rottweil', dataset: 'counties', id: 8325},
    {label: 'Schwarzwald-Baar-Kreis', dataset: 'counties', id: 8326},
    {label: 'Tuttlingen', dataset: 'counties', id: 8327},
    {label: 'Konstanz', dataset: 'counties', id: 8335},
    {label: 'Lörrach', dataset: 'counties', id: 8336},
    {label: 'Waldshut', dataset: 'counties', id: 8337},
    {label: 'Reutlingen', dataset: 'counties', id: 8415},
    {label: 'Tübingen', dataset: 'counties', id: 8416},
    {label: 'Zollernalbkreis', dataset: 'counties', id: 8417},
    {label: 'Ulm', dataset: 'counties', id: 8421},
    {label: 'Alb-Donau-Kreis', dataset: 'counties', id: 8425},
    {label: 'Biberach', dataset: 'counties', id: 8426},
    {label: 'Bodenseekreis', dataset: 'counties', id: 8435},
    {label: 'Ravensburg', dataset: 'counties', id: 8436},
    {label: 'Sigmaringen', dataset: 'counties', id: 8437},
    {label: 'Ingolstadt', dataset: 'counties', id: 9161},
    {label: 'München', dataset: 'counties', id: 9162},
    {label: 'Rosenheim', dataset: 'counties', id: 9163},
    {label: 'Altötting', dataset: 'counties', id: 9171},
    {label: 'Berchtesgadener Land', dataset: 'counties', id: 9172},
    {label: 'Bad Tölz-Wolfratshausen', dataset: 'counties', id: 9173},
    {label: 'Dachau', dataset: 'counties', id: 9174},
    {label: 'Ebersberg', dataset: 'counties', id: 9175},
    {label: 'Eichstätt', dataset: 'counties', id: 9176},
    {label: 'Erding', dataset: 'counties', id: 9177},
    {label: 'Freising', dataset: 'counties', id: 9178},
    {label: 'Fürstenfeldbruck', dataset: 'counties', id: 9179},
    {label: 'Garmisch-Partenkirchen', dataset: 'counties', id: 9180},
    {label: 'Landsberg am Lech', dataset: 'counties', id: 9181},
    {label: 'Miesbach', dataset: 'counties', id: 9182},
    {label: 'Mühldorf a. Inn', dataset: 'counties', id: 9183},
    {label: 'München', dataset: 'counties', id: 9184},
    {label: 'Neuburg-Schrobenhausen', dataset: 'counties', id: 9185},
    {label: 'Pfaffenhofen a.d. Ilm', dataset: 'counties', id: 9186},
    {label: 'Rosenheim', dataset: 'counties', id: 9187},
    {label: 'Starnberg', dataset: 'counties', id: 9188},
    {label: 'Traunstein', dataset: 'counties', id: 9189},
    {label: 'Weilheim-Schongau', dataset: 'counties', id: 9190},
    {label: 'Landshut', dataset: 'counties', id: 9261},
    {label: 'Passau', dataset: 'counties', id: 9262},
    {label: 'Straubing', dataset: 'counties', id: 9263},
    {label: 'Deggendorf', dataset: 'counties', id: 9271},
    {label: 'Freyung-Grafenau', dataset: 'counties', id: 9272},
    {label: 'Kelheim', dataset: 'counties', id: 9273},
    {label: 'Landshut', dataset: 'counties', id: 9274},
    {label: 'Passau', dataset: 'counties', id: 9275},
    {label: 'Regen', dataset: 'counties', id: 9276},
    {label: 'Rottal-Inn', dataset: 'counties', id: 9277},
    {label: 'Straubing-Bogen', dataset: 'counties', id: 9278},
    {label: 'Dingolfing-Landau', dataset: 'counties', id: 9279},
    {label: 'Amberg', dataset: 'counties', id: 9361},
    {label: 'Regensburg', dataset: 'counties', id: 9362},
    {label: 'Weiden i.d. OPf.', dataset: 'counties', id: 9363},
    {label: 'Amberg-Sulzbach', dataset: 'counties', id: 9371},
    {label: 'Cham', dataset: 'counties', id: 9372},
    {label: 'Neumarkt i.d. OPf.', dataset: 'counties', id: 9373},
    {label: 'Neustadt a.d. Waldnaab', dataset: 'counties', id: 9374},
    {label: 'Regensburg', dataset: 'counties', id: 9375},
    {label: 'Schwandorf', dataset: 'counties', id: 9376},
    {label: 'Tirschenreuth', dataset: 'counties', id: 9377},
    {label: 'Bamberg', dataset: 'counties', id: 9461},
    {label: 'Bayreuth', dataset: 'counties', id: 9462},
    {label: 'Coburg', dataset: 'counties', id: 9463},
    {label: 'Hof', dataset: 'counties', id: 9464},
    {label: 'Bamberg', dataset: 'counties', id: 9471},
    {label: 'Bayreuth', dataset: 'counties', id: 9472},
    {label: 'Coburg', dataset: 'counties', id: 9473},
    {label: 'Forchheim', dataset: 'counties', id: 9474},
    {label: 'Hof', dataset: 'counties', id: 9475},
    {label: 'Kronach', dataset: 'counties', id: 9476},
    {label: 'Kulmbach', dataset: 'counties', id: 9477},
    {label: 'Lichtenfels', dataset: 'counties', id: 9478},
    {label: 'Wunsiedel i. Fichtelgebirge', dataset: 'counties', id: 9479},
    {label: 'Ansbach', dataset: 'counties', id: 9561},
    {label: 'Erlangen', dataset: 'counties', id: 9562},
    {label: 'Fürth', dataset: 'counties', id: 9563},
    {label: 'Nürnberg', dataset: 'counties', id: 9564},
    {label: 'Schwabach', dataset: 'counties', id: 9565},
    {label: 'Ansbach', dataset: 'counties', id: 9571},
    {label: 'Erlangen-Höchstadt', dataset: 'counties', id: 9572},
    {label: 'Fürth', dataset: 'counties', id: 9573},
    {label: 'Nürnberger Land', dataset: 'counties', id: 9574},
    {label: 'Neustadt a.d. Aisch-Bad Windsheim', dataset: 'counties', id: 9575},
    {label: 'Roth', dataset: 'counties', id: 9576},
    {label: 'Weißenburg-Gunzenhausen', dataset: 'counties', id: 9577},
    {label: 'Aschaffenburg', dataset: 'counties', id: 9661},
    {label: 'Schweinfurt', dataset: 'counties', id: 9662},
    {label: 'Würzburg', dataset: 'counties', id: 9663},
    {label: 'Aschaffenburg', dataset: 'counties', id: 9671},
    {label: 'Bad Kissingen', dataset: 'counties', id: 9672},
    {label: 'Rhön-Grabfeld', dataset: 'counties', id: 9673},
    {label: 'Haßberge', dataset: 'counties', id: 9674},
    {label: 'Kitzingen', dataset: 'counties', id: 9675},
    {label: 'Miltenberg', dataset: 'counties', id: 9676},
    {label: 'Main-Spessart', dataset: 'counties', id: 9677},
    {label: 'Schweinfurt', dataset: 'counties', id: 9678},
    {label: 'Würzburg', dataset: 'counties', id: 9679},
    {label: 'Augsburg', dataset: 'counties', id: 9761},
    {label: 'Kaufbeuren', dataset: 'counties', id: 9762},
    {label: 'Kempten (Allgäu)', dataset: 'counties', id: 9763},
    {label: 'Memmingen', dataset: 'counties', id: 9764},
    {label: 'Aichach-Friedberg', dataset: 'counties', id: 9771},
    {label: 'Augsburg', dataset: 'counties', id: 9772},
    {label: 'Dillingen a.d. Donau', dataset: 'counties', id: 9773},
    {label: 'Günzburg', dataset: 'counties', id: 9774},
    {label: 'Neu-Ulm', dataset: 'counties', id: 9775},
    {label: 'Lindau (Bodensee)', dataset: 'counties', id: 9776},
    {label: 'Ostallgäu', dataset: 'counties', id: 9777},
    {label: 'Unterallgäu', dataset: 'counties', id: 9778},
    {label: 'Donau-Ries', dataset: 'counties', id: 9779},
    {label: 'Oberallgäu', dataset: 'counties', id: 9780},
    {label: 'Regionalverband Saarbrücken', dataset: 'counties', id: 10041},
    {label: 'Merzig-Wadern', dataset: 'counties', id: 10042},
    {label: 'Neunkirchen', dataset: 'counties', id: 10043},
    {label: 'Saarlouis', dataset: 'counties', id: 10044},
    {label: 'Saarpfalz-Kreis', dataset: 'counties', id: 10045},
    {label: 'St. Wendel', dataset: 'counties', id: 10046},
    {label: 'Berlin', dataset: 'counties', id: 11001},
    {label: 'Brandenburg an der Havel', dataset: 'counties', id: 11002},
    {label: 'Cottbus', dataset: 'counties', id: 11003},
    {label: 'Frankfurt (Oder)', dataset: 'counties', id: 11004},
    {label: 'Potsdam', dataset: 'counties', id: 11005},
    {label: 'Barnim', dataset: 'counties', id: 11006},
    {label: 'Dahme-Spreewald', dataset: 'counties', id: 11007},
    {label: 'Elbe-Elster', dataset: 'counties', id: 11008},
    {label: 'Havelland', dataset: 'counties', id: 11009},
    {label: 'Märkisch-Oderland', dataset: 'counties', id: 11010},
    {label: 'Oberhavel', dataset: 'counties', id: 11011},
    {label: 'Oberspreewald-Lausitz', dataset: 'counties', id: 11012},
    {label: 'Oder-Spree', dataset: 'counties', id: 12051},
    {label: 'Ostprignitz-Ruppin', dataset: 'counties', id: 12052},
    {label: 'Potsdam-Mittelmark', dataset: 'counties', id: 12053},
    {label: 'Prignitz', dataset: 'counties', id: 12054},
    {label: 'Spree-Neiße', dataset: 'counties', id: 12060},
    {label: 'Teltow-Fläming', dataset: 'counties', id: 12061},
    {label: 'Uckermark', dataset: 'counties', id: 12062},
    {label: 'Rostock', dataset: 'counties', id: 12063},
    {label: 'Schwerin', dataset: 'counties', id: 12064},
    {label: 'Mecklenburgische Seenplatte', dataset: 'counties', id: 12065},
    {label: 'Rostock', dataset: 'counties', id: 12066},
    {label: 'Vorpommern-Rügen', dataset: 'counties', id: 12067},
    {label: 'Nordwestmecklenburg', dataset: 'counties', id: 12068},
    {label: 'Vorpommern-Greifswald', dataset: 'counties', id: 12069},
    {label: 'Ludwigslust-Parchim', dataset: 'counties', id: 12070},
    {label: 'Chemnitz', dataset: 'counties', id: 12071},
    {label: 'Erzgebirgskreis', dataset: 'counties', id: 12072},
    {label: 'Mittelsachsen', dataset: 'counties', id: 12073},
    {label: 'Vogtlandkreis', dataset: 'counties', id: 13003},
    {label: 'Zwickau', dataset: 'counties', id: 13004},
    {label: 'Dresden', dataset: 'counties', id: 13071},
    {label: 'Bautzen', dataset: 'counties', id: 13072},
    {label: 'Görlitz', dataset: 'counties', id: 13073},
    {label: 'Meißen', dataset: 'counties', id: 13074},
    {label: 'Sächsische Schweiz-Osterzgebirge', dataset: 'counties', id: 13075},
    {label: 'Leipzig', dataset: 'counties', id: 13076},
    {label: 'Leipzig', dataset: 'counties', id: 14511},
    {label: 'Nordsachsen', dataset: 'counties', id: 14521},
    {label: 'Dessau-Roßlau', dataset: 'counties', id: 14522},
    {label: 'Halle (Saale)', dataset: 'counties', id: 14523},
    {label: 'Magdeburg', dataset: 'counties', id: 14524},
    {label: 'Altmarkkreis Salzwedel', dataset: 'counties', id: 14612},
    {label: 'Anhalt-Bitterfeld', dataset: 'counties', id: 14625},
    {label: 'Börde', dataset: 'counties', id: 14626},
    {label: 'Burgenlandkreis', dataset: 'counties', id: 14627},
    {label: 'Harz', dataset: 'counties', id: 14628},
    {label: 'Jerichower Land', dataset: 'counties', id: 14713},
    {label: 'Mansfeld-Südharz', dataset: 'counties', id: 14729},
    {label: 'Saalekreis', dataset: 'counties', id: 14730},
    {label: 'Salzlandkreis', dataset: 'counties', id: 15001},
    {label: 'Stendal', dataset: 'counties', id: 15002},
    {label: 'Wittenberg', dataset: 'counties', id: 15003},
    {label: 'Erfurt', dataset: 'counties', id: 15081},
    {label: 'Gera', dataset: 'counties', id: 15082},
    {label: 'Jena', dataset: 'counties', id: 15083},
    {label: 'Suhl', dataset: 'counties', id: 15084},
    {label: 'Weimar', dataset: 'counties', id: 15085},
    {label: 'Eisenach', dataset: 'counties', id: 15086},
    {label: 'Eichsfeld', dataset: 'counties', id: 15087},
    {label: 'Nordhausen', dataset: 'counties', id: 15088},
    {label: 'Wartburgkreis', dataset: 'counties', id: 15089},
    {label: 'Unstrut-Hainich-Kreis', dataset: 'counties', id: 15090},
    {label: 'Kyffhäuserkreis', dataset: 'counties', id: 15091},
    {label: 'Schmalkalden-Meiningen', dataset: 'counties', id: 16051},
    {label: 'Gotha', dataset: 'counties', id: 16052},
    {label: 'Sömmerda', dataset: 'counties', id: 16053},
    {label: 'Hildburghausen', dataset: 'counties', id: 16054},
    {label: 'Ilm-Kreis', dataset: 'counties', id: 16055},
    {label: 'Weimarer Land', dataset: 'counties', id: 16056},
    {label: 'Sonneberg', dataset: 'counties', id: 16061},
    {label: 'Saalfeld-Rudolstadt', dataset: 'counties', id: 16062},
    {label: 'Saale-Holzland-Kreis', dataset: 'counties', id: 16063},
    {label: 'Saale-Orla-Kreis', dataset: 'counties', id: 16064},
    {label: 'Greiz', dataset: 'counties', id: 16065},
    {label: 'Altenburger Land', dataset: 'counties', id: 16066},
  ],
};

export default Regions;
