const Regions = {
  GERMANY: {dataset: 'germany', id: '0', label: 'Germany'},
  STATES: [
    {id: '01', dataset: 'states', label: 'Schleswig-Holstein'},
    {id: '02', dataset: 'states', label: 'Hamburg'},
    {id: '03', dataset: 'states', label: 'Niedersachsen'},
    {id: '04', dataset: 'states', label: 'Bremen'},
    {id: '05', dataset: 'states', label: 'Nordrhein-Westfalen'},
    {id: '06', dataset: 'states', label: 'Hessen'},
    {id: '07', dataset: 'states', label: 'Rheinland-Pfalz'},
    {id: '08', dataset: 'states', label: 'Baden-Württemberg'},
    {id: '09', dataset: 'states', label: 'Bayern'},
    {id: '10', dataset: 'states', label: 'Saarland'},
    {id: '11', dataset: 'states', label: 'Berlin'},
    {id: '12', dataset: 'states', label: 'Brandenburg'},
    {id: '13', dataset: 'states', label: 'Mecklenburg-Vorpommern'},
    {id: '14', dataset: 'states', label: 'Sachsen'},
    {id: '15', dataset: 'states', label: 'Sachsen-Anhalt'},
    {id: '16', dataset: 'states', label: 'Thüringen'},
  ],
  // AUTO GENERATED
  COUNTIES: [
    {label: 'Flensburg', dataset: 'counties', id: '01001'},
    {label: 'Kiel', dataset: 'counties', id: '01002'},
    {label: 'Lübeck', dataset: 'counties', id: '01003'},
    {label: 'Neumünster', dataset: 'counties', id: '01004'},
    {label: 'Dithmarschen', dataset: 'counties', id: '01051'},
    {label: 'Herzogtum Lauenburg', dataset: 'counties', id: '01053'},
    {label: 'Nordfriesland', dataset: 'counties', id: '01054'},
    {label: 'Ostholstein', dataset: 'counties', id: '01055'},
    {label: 'Pinneberg', dataset: 'counties', id: '01056'},
    {label: 'Plön', dataset: 'counties', id: '01057'},
    {label: 'Rendsburg-Eckernförde', dataset: 'counties', id: '01058'},
    {label: 'Schleswig-Flensburg', dataset: 'counties', id: '01059'},
    {label: 'Segeberg', dataset: 'counties', id: '01060'},
    {label: 'Steinburg', dataset: 'counties', id: '01061'},
    {label: 'Stormarn', dataset: 'counties', id: '01062'},
    {label: 'Hamburg', dataset: 'counties', id: '02000'},
    {label: 'Braunschweig', dataset: 'counties', id: '03101'},
    {label: 'Salzgitter', dataset: 'counties', id: '03102'},
    {label: 'Wolfsburg', dataset: 'counties', id: '03103'},
    {label: 'Gifhorn', dataset: 'counties', id: '03151'},
    {label: 'Goslar', dataset: 'counties', id: '03153'},
    {label: 'Helmstedt', dataset: 'counties', id: '03154'},
    {label: 'Northeim', dataset: 'counties', id: '03155'},
    {label: 'Peine', dataset: 'counties', id: '03157'},
    {label: 'Wolfenbüttel', dataset: 'counties', id: '03158'},
    {label: 'Göttingen', dataset: 'counties', id: '03159'},
    {label: 'Region Hannover', dataset: 'counties', id: '03241'},
    {label: 'Diepholz', dataset: 'counties', id: '03251'},
    {label: 'Hameln-Pyrmont', dataset: 'counties', id: '03252'},
    {label: 'Hildesheim', dataset: 'counties', id: '03254'},
    {label: 'Holzminden', dataset: 'counties', id: '03255'},
    {label: 'Nienburg (Weser)', dataset: 'counties', id: '03256'},
    {label: 'Schaumburg', dataset: 'counties', id: '03257'},
    {label: 'Celle', dataset: 'counties', id: '03351'},
    {label: 'Cuxhaven', dataset: 'counties', id: '03352'},
    {label: 'Harburg', dataset: 'counties', id: '03353'},
    {label: 'Lüchow-Dannenberg', dataset: 'counties', id: '03354'},
    {label: 'Lüneburg', dataset: 'counties', id: '03355'},
    {label: 'Osterholz', dataset: 'counties', id: '03356'},
    {label: 'Rotenburg (Wümme)', dataset: 'counties', id: '03357'},
    {label: 'Heidekreis', dataset: 'counties', id: '03358'},
    {label: 'Stade', dataset: 'counties', id: '03359'},
    {label: 'Uelzen', dataset: 'counties', id: '03360'},
    {label: 'Verden', dataset: 'counties', id: '03361'},
    {label: 'Delmenhorst', dataset: 'counties', id: '03401'},
    {label: 'Emden', dataset: 'counties', id: '03402'},
    {label: 'Oldenburg (Oldb)', dataset: 'counties', id: '03403'},
    {label: 'Osnabrück', dataset: 'counties', id: '03404'},
    {label: 'Wilhelmshaven', dataset: 'counties', id: '03405'},
    {label: 'Ammerland', dataset: 'counties', id: '03451'},
    {label: 'Aurich', dataset: 'counties', id: '03452'},
    {label: 'Cloppenburg', dataset: 'counties', id: '03453'},
    {label: 'Emsland', dataset: 'counties', id: '03454'},
    {label: 'Friesland', dataset: 'counties', id: '03455'},
    {label: 'Grafschaft Bentheim', dataset: 'counties', id: '03456'},
    {label: 'Leer', dataset: 'counties', id: '03457'},
    {label: 'Oldenburg', dataset: 'counties', id: '03458'},
    {label: 'Osnabrück', dataset: 'counties', id: '03459'},
    {label: 'Vechta', dataset: 'counties', id: '03460'},
    {label: 'Wesermarsch', dataset: 'counties', id: '03461'},
    {label: 'Wittmund', dataset: 'counties', id: '03462'},
    {label: 'Bremen', dataset: 'counties', id: '04011'},
    {label: 'Bremerhaven', dataset: 'counties', id: '04012'},
    {label: 'Düsseldorf', dataset: 'counties', id: '05111'},
    {label: 'Duisburg', dataset: 'counties', id: '05112'},
    {label: 'Essen', dataset: 'counties', id: '05113'},
    {label: 'Krefeld', dataset: 'counties', id: '05114'},
    {label: 'Mönchengladbach', dataset: 'counties', id: '05116'},
    {label: 'Mülheim an der Ruhr', dataset: 'counties', id: '05117'},
    {label: 'Oberhausen', dataset: 'counties', id: '05119'},
    {label: 'Remscheid', dataset: 'counties', id: '05120'},
    {label: 'Solingen', dataset: 'counties', id: '05122'},
    {label: 'Wuppertal', dataset: 'counties', id: '05124'},
    {label: 'Kleve', dataset: 'counties', id: '05154'},
    {label: 'Mettmann', dataset: 'counties', id: '05158'},
    {label: 'Rhein-Kreis Neuss', dataset: 'counties', id: '05162'},
    {label: 'Viersen', dataset: 'counties', id: '05166'},
    {label: 'Wesel', dataset: 'counties', id: '05170'},
    {label: 'Bonn', dataset: 'counties', id: '05314'},
    {label: 'Köln', dataset: 'counties', id: '05315'},
    {label: 'Leverkusen', dataset: 'counties', id: '05316'},
    {label: 'Städteregion Aachen', dataset: 'counties', id: '05334'},
    {label: 'Düren', dataset: 'counties', id: '05358'},
    {label: 'Rhein-Erft-Kreis', dataset: 'counties', id: '05362'},
    {label: 'Euskirchen', dataset: 'counties', id: '05366'},
    {label: 'Heinsberg', dataset: 'counties', id: '05370'},
    {label: 'Oberbergischer Kreis', dataset: 'counties', id: '05374'},
    {label: 'Rheinisch-Bergischer Kreis', dataset: 'counties', id: '05378'},
    {label: 'Rhein-Sieg-Kreis', dataset: 'counties', id: '05382'},
    {label: 'Bottrop', dataset: 'counties', id: '05512'},
    {label: 'Gelsenkirchen', dataset: 'counties', id: '05513'},
    {label: 'Münster', dataset: 'counties', id: '05515'},
    {label: 'Borken', dataset: 'counties', id: '05554'},
    {label: 'Coesfeld', dataset: 'counties', id: '05558'},
    {label: 'Recklinghausen', dataset: 'counties', id: '05562'},
    {label: 'Steinfurt', dataset: 'counties', id: '05566'},
    {label: 'Warendorf', dataset: 'counties', id: '05570'},
    {label: 'Bielefeld', dataset: 'counties', id: '05711'},
    {label: 'Gütersloh', dataset: 'counties', id: '05754'},
    {label: 'Herford', dataset: 'counties', id: '05758'},
    {label: 'Höxter', dataset: 'counties', id: '05762'},
    {label: 'Lippe', dataset: 'counties', id: '05766'},
    {label: 'Minden-Lübbecke', dataset: 'counties', id: '05770'},
    {label: 'Paderborn', dataset: 'counties', id: '05774'},
    {label: 'Bochum', dataset: 'counties', id: '05911'},
    {label: 'Dortmund', dataset: 'counties', id: '05913'},
    {label: 'Hagen', dataset: 'counties', id: '05914'},
    {label: 'Hamm', dataset: 'counties', id: '05915'},
    {label: 'Herne', dataset: 'counties', id: '05916'},
    {label: 'Ennepe-Ruhr-Kreis', dataset: 'counties', id: '05954'},
    {label: 'Hochsauerlandkreis', dataset: 'counties', id: '05958'},
    {label: 'Märkischer Kreis', dataset: 'counties', id: '05962'},
    {label: 'Olpe', dataset: 'counties', id: '05966'},
    {label: 'Siegen-Wittgenstein', dataset: 'counties', id: '05970'},
    {label: 'Soest', dataset: 'counties', id: '05974'},
    {label: 'Unna', dataset: 'counties', id: '05978'},
    {label: 'Darmstadt', dataset: 'counties', id: '06411'},
    {label: 'Frankfurt am Main', dataset: 'counties', id: '06412'},
    {label: 'Offenbach am Main', dataset: 'counties', id: '06413'},
    {label: 'Wiesbaden', dataset: 'counties', id: '06414'},
    {label: 'Bergstraße', dataset: 'counties', id: '06431'},
    {label: 'Darmstadt-Dieburg', dataset: 'counties', id: '06432'},
    {label: 'Groß-Gerau', dataset: 'counties', id: '06433'},
    {label: 'Hochtaunuskreis', dataset: 'counties', id: '06434'},
    {label: 'Main-Kinzig-Kreis', dataset: 'counties', id: '06435'},
    {label: 'Main-Taunus-Kreis', dataset: 'counties', id: '06436'},
    {label: 'Odenwaldkreis', dataset: 'counties', id: '06437'},
    {label: 'Offenbach', dataset: 'counties', id: '06438'},
    {label: 'Rheingau-Taunus-Kreis', dataset: 'counties', id: '06439'},
    {label: 'Wetteraukreis', dataset: 'counties', id: '06440'},
    {label: 'Gießen', dataset: 'counties', id: '06531'},
    {label: 'Lahn-Dill-Kreis', dataset: 'counties', id: '06532'},
    {label: 'Limburg-Weilburg', dataset: 'counties', id: '06533'},
    {label: 'Marburg-Biedenkopf', dataset: 'counties', id: '06534'},
    {label: 'Vogelsbergkreis', dataset: 'counties', id: '06535'},
    {label: 'Kassel', dataset: 'counties', id: '06611'},
    {label: 'Fulda', dataset: 'counties', id: '06631'},
    {label: 'Hersfeld-Rotenburg', dataset: 'counties', id: '06632'},
    {label: 'Kassel', dataset: 'counties', id: '06633'},
    {label: 'Schwalm-Eder-Kreis', dataset: 'counties', id: '06634'},
    {label: 'Waldeck-Frankenberg', dataset: 'counties', id: '06635'},
    {label: 'Werra-Meißner-Kreis', dataset: 'counties', id: '06636'},
    {label: 'Koblenz', dataset: 'counties', id: '07111'},
    {label: 'Ahrweiler', dataset: 'counties', id: '07131'},
    {label: 'Altenkirchen (Westerwald)', dataset: 'counties', id: '07132'},
    {label: 'Bad Kreuznach', dataset: 'counties', id: '07133'},
    {label: 'Birkenfeld', dataset: 'counties', id: '07134'},
    {label: 'Cochem-Zell', dataset: 'counties', id: '07135'},
    {label: 'Mayen-Koblenz', dataset: 'counties', id: '07137'},
    {label: 'Neuwied', dataset: 'counties', id: '07138'},
    {label: 'Rhein-Hunsrück-Kreis', dataset: 'counties', id: '07140'},
    {label: 'Rhein-Lahn-Kreis', dataset: 'counties', id: '07141'},
    {label: 'Westerwaldkreis', dataset: 'counties', id: '07143'},
    {label: 'Trier', dataset: 'counties', id: '07211'},
    {label: 'Bernkastel-Wittlich', dataset: 'counties', id: '07231'},
    {label: 'Eifelkreis Bitburg-Prüm', dataset: 'counties', id: '07232'},
    {label: 'Vulkaneifel', dataset: 'counties', id: '07233'},
    {label: 'Trier-Saarburg', dataset: 'counties', id: '07235'},
    {label: 'Frankenthal (Pfalz)', dataset: 'counties', id: '07311'},
    {label: 'Kaiserslautern', dataset: 'counties', id: '07312'},
    {label: 'Landau in der Pfalz', dataset: 'counties', id: '07313'},
    {label: 'Ludwigshafen am Rhein', dataset: 'counties', id: '07314'},
    {label: 'Mainz', dataset: 'counties', id: '07315'},
    {label: 'Neustadt an der Weinstraße', dataset: 'counties', id: '07316'},
    {label: 'Pirmasens', dataset: 'counties', id: '07317'},
    {label: 'Speyer', dataset: 'counties', id: '07318'},
    {label: 'Worms', dataset: 'counties', id: '07319'},
    {label: 'Zweibrücken', dataset: 'counties', id: '07320'},
    {label: 'Alzey-Worms', dataset: 'counties', id: '07331'},
    {label: 'Bad Dürkheim', dataset: 'counties', id: '07332'},
    {label: 'Donnersbergkreis', dataset: 'counties', id: '07333'},
    {label: 'Germersheim', dataset: 'counties', id: '07334'},
    {label: 'Kaiserslautern', dataset: 'counties', id: '07335'},
    {label: 'Kusel', dataset: 'counties', id: '07336'},
    {label: 'Südliche Weinstraße', dataset: 'counties', id: '07337'},
    {label: 'Rhein-Pfalz-Kreis', dataset: 'counties', id: '07338'},
    {label: 'Mainz-Bingen', dataset: 'counties', id: '07339'},
    {label: 'Südwestpfalz', dataset: 'counties', id: '07340'},
    {label: 'Stuttgart', dataset: 'counties', id: '08111'},
    {label: 'Böblingen', dataset: 'counties', id: '08115'},
    {label: 'Esslingen', dataset: 'counties', id: '08116'},
    {label: 'Göppingen', dataset: 'counties', id: '08117'},
    {label: 'Ludwigsburg', dataset: 'counties', id: '08118'},
    {label: 'Rems-Murr-Kreis', dataset: 'counties', id: '08119'},
    {label: 'Heilbronn', dataset: 'counties', id: '08121'},
    {label: 'Heilbronn', dataset: 'counties', id: '08125'},
    {label: 'Hohenlohekreis', dataset: 'counties', id: '08126'},
    {label: 'Schwäbisch Hall', dataset: 'counties', id: '08127'},
    {label: 'Main-Tauber-Kreis', dataset: 'counties', id: '08128'},
    {label: 'Heidenheim', dataset: 'counties', id: '08135'},
    {label: 'Ostalbkreis', dataset: 'counties', id: '08136'},
    {label: 'Baden-Baden', dataset: 'counties', id: '08211'},
    {label: 'Karlsruhe', dataset: 'counties', id: '08212'},
    {label: 'Karlsruhe', dataset: 'counties', id: '08215'},
    {label: 'Rastatt', dataset: 'counties', id: '08216'},
    {label: 'Heidelberg', dataset: 'counties', id: '08221'},
    {label: 'Mannheim', dataset: 'counties', id: '08222'},
    {label: 'Neckar-Odenwald-Kreis', dataset: 'counties', id: '08225'},
    {label: 'Rhein-Neckar-Kreis', dataset: 'counties', id: '08226'},
    {label: 'Pforzheim', dataset: 'counties', id: '08231'},
    {label: 'Calw', dataset: 'counties', id: '08235'},
    {label: 'Enzkreis', dataset: 'counties', id: '08236'},
    {label: 'Freudenstadt', dataset: 'counties', id: '08237'},
    {label: 'Freiburg im Breisgau', dataset: 'counties', id: '08311'},
    {label: 'Breisgau-Hochschwarzwald', dataset: 'counties', id: '08315'},
    {label: 'Emmendingen', dataset: 'counties', id: '08316'},
    {label: 'Ortenaukreis', dataset: 'counties', id: '08317'},
    {label: 'Rottweil', dataset: 'counties', id: '08325'},
    {label: 'Schwarzwald-Baar-Kreis', dataset: 'counties', id: '08326'},
    {label: 'Tuttlingen', dataset: 'counties', id: '08327'},
    {label: 'Konstanz', dataset: 'counties', id: '08335'},
    {label: 'Lörrach', dataset: 'counties', id: '08336'},
    {label: 'Waldshut', dataset: 'counties', id: '08337'},
    {label: 'Reutlingen', dataset: 'counties', id: '08415'},
    {label: 'Tübingen', dataset: 'counties', id: '08416'},
    {label: 'Zollernalbkreis', dataset: 'counties', id: '08417'},
    {label: 'Ulm', dataset: 'counties', id: '08421'},
    {label: 'Alb-Donau-Kreis', dataset: 'counties', id: '08425'},
    {label: 'Biberach', dataset: 'counties', id: '08426'},
    {label: 'Bodenseekreis', dataset: 'counties', id: '08435'},
    {label: 'Ravensburg', dataset: 'counties', id: '08436'},
    {label: 'Sigmaringen', dataset: 'counties', id: '08437'},
    {label: 'Ingolstadt', dataset: 'counties', id: '09161'},
    {label: 'München', dataset: 'counties', id: '09162'},
    {label: 'Rosenheim', dataset: 'counties', id: '09163'},
    {label: 'Altötting', dataset: 'counties', id: '09171'},
    {label: 'Berchtesgadener Land', dataset: 'counties', id: '09172'},
    {label: 'Bad Tölz-Wolfratshausen', dataset: 'counties', id: '09173'},
    {label: 'Dachau', dataset: 'counties', id: '09174'},
    {label: 'Ebersberg', dataset: 'counties', id: '09175'},
    {label: 'Eichstätt', dataset: 'counties', id: '09176'},
    {label: 'Erding', dataset: 'counties', id: '09177'},
    {label: 'Freising', dataset: 'counties', id: '09178'},
    {label: 'Fürstenfeldbruck', dataset: 'counties', id: '09179'},
    {label: 'Garmisch-Partenkirchen', dataset: 'counties', id: '09180'},
    {label: 'Landsberg am Lech', dataset: 'counties', id: '09181'},
    {label: 'Miesbach', dataset: 'counties', id: '09182'},
    {label: 'Mühldorf a. Inn', dataset: 'counties', id: '09183'},
    {label: 'München', dataset: 'counties', id: '09184'},
    {label: 'Neuburg-Schrobenhausen', dataset: 'counties', id: '09185'},
    {label: 'Pfaffenhofen a.d. Ilm', dataset: 'counties', id: '09186'},
    {label: 'Rosenheim', dataset: 'counties', id: '09187'},
    {label: 'Starnberg', dataset: 'counties', id: '09188'},
    {label: 'Traunstein', dataset: 'counties', id: '09189'},
    {label: 'Weilheim-Schongau', dataset: 'counties', id: '09190'},
    {label: 'Landshut', dataset: 'counties', id: '09261'},
    {label: 'Passau', dataset: 'counties', id: '09262'},
    {label: 'Straubing', dataset: 'counties', id: '09263'},
    {label: 'Deggendorf', dataset: 'counties', id: '09271'},
    {label: 'Freyung-Grafenau', dataset: 'counties', id: '09272'},
    {label: 'Kelheim', dataset: 'counties', id: '09273'},
    {label: 'Landshut', dataset: 'counties', id: '09274'},
    {label: 'Passau', dataset: 'counties', id: '09275'},
    {label: 'Regen', dataset: 'counties', id: '09276'},
    {label: 'Rottal-Inn', dataset: 'counties', id: '09277'},
    {label: 'Straubing-Bogen', dataset: 'counties', id: '09278'},
    {label: 'Dingolfing-Landau', dataset: 'counties', id: '09279'},
    {label: 'Amberg', dataset: 'counties', id: '09361'},
    {label: 'Regensburg', dataset: 'counties', id: '09362'},
    {label: 'Weiden i.d. OPf.', dataset: 'counties', id: '09363'},
    {label: 'Amberg-Sulzbach', dataset: 'counties', id: '09371'},
    {label: 'Cham', dataset: 'counties', id: '09372'},
    {label: 'Neumarkt i.d. OPf.', dataset: 'counties', id: '09373'},
    {label: 'Neustadt a.d. Waldnaab', dataset: 'counties', id: '09374'},
    {label: 'Regensburg', dataset: 'counties', id: '09375'},
    {label: 'Schwandorf', dataset: 'counties', id: '09376'},
    {label: 'Tirschenreuth', dataset: 'counties', id: '09377'},
    {label: 'Bamberg', dataset: 'counties', id: '09461'},
    {label: 'Bayreuth', dataset: 'counties', id: '09462'},
    {label: 'Coburg', dataset: 'counties', id: '09463'},
    {label: 'Hof', dataset: 'counties', id: '09464'},
    {label: 'Bamberg', dataset: 'counties', id: '09471'},
    {label: 'Bayreuth', dataset: 'counties', id: '09472'},
    {label: 'Coburg', dataset: 'counties', id: '09473'},
    {label: 'Forchheim', dataset: 'counties', id: '09474'},
    {label: 'Hof', dataset: 'counties', id: '09475'},
    {label: 'Kronach', dataset: 'counties', id: '09476'},
    {label: 'Kulmbach', dataset: 'counties', id: '09477'},
    {label: 'Lichtenfels', dataset: 'counties', id: '09478'},
    {label: 'Wunsiedel i. Fichtelgebirge', dataset: 'counties', id: '09479'},
    {label: 'Ansbach', dataset: 'counties', id: '09561'},
    {label: 'Erlangen', dataset: 'counties', id: '09562'},
    {label: 'Fürth', dataset: 'counties', id: '09563'},
    {label: 'Nürnberg', dataset: 'counties', id: '09564'},
    {label: 'Schwabach', dataset: 'counties', id: '09565'},
    {label: 'Ansbach', dataset: 'counties', id: '09571'},
    {label: 'Erlangen-Höchstadt', dataset: 'counties', id: '09572'},
    {label: 'Fürth', dataset: 'counties', id: '09573'},
    {label: 'Nürnberger Land', dataset: 'counties', id: '09574'},
    {label: 'Neustadt a.d. Aisch-Bad Windsheim', dataset: 'counties', id: '09575'},
    {label: 'Roth', dataset: 'counties', id: '09576'},
    {label: 'Weißenburg-Gunzenhausen', dataset: 'counties', id: '09577'},
    {label: 'Aschaffenburg', dataset: 'counties', id: '09661'},
    {label: 'Schweinfurt', dataset: 'counties', id: '09662'},
    {label: 'Würzburg', dataset: 'counties', id: '09663'},
    {label: 'Aschaffenburg', dataset: 'counties', id: '09671'},
    {label: 'Bad Kissingen', dataset: 'counties', id: '09672'},
    {label: 'Rhön-Grabfeld', dataset: 'counties', id: '09673'},
    {label: 'Haßberge', dataset: 'counties', id: '09674'},
    {label: 'Kitzingen', dataset: 'counties', id: '09675'},
    {label: 'Miltenberg', dataset: 'counties', id: '09676'},
    {label: 'Main-Spessart', dataset: 'counties', id: '09677'},
    {label: 'Schweinfurt', dataset: 'counties', id: '09678'},
    {label: 'Würzburg', dataset: 'counties', id: '09679'},
    {label: 'Augsburg', dataset: 'counties', id: '09761'},
    {label: 'Kaufbeuren', dataset: 'counties', id: '09762'},
    {label: 'Kempten (Allgäu)', dataset: 'counties', id: '09763'},
    {label: 'Memmingen', dataset: 'counties', id: '09764'},
    {label: 'Aichach-Friedberg', dataset: 'counties', id: '09771'},
    {label: 'Augsburg', dataset: 'counties', id: '09772'},
    {label: 'Dillingen a.d. Donau', dataset: 'counties', id: '09773'},
    {label: 'Günzburg', dataset: 'counties', id: '09774'},
    {label: 'Neu-Ulm', dataset: 'counties', id: '09775'},
    {label: 'Lindau (Bodensee)', dataset: 'counties', id: '09776'},
    {label: 'Ostallgäu', dataset: 'counties', id: '09777'},
    {label: 'Unterallgäu', dataset: 'counties', id: '09778'},
    {label: 'Donau-Ries', dataset: 'counties', id: '09779'},
    {label: 'Oberallgäu', dataset: 'counties', id: '09780'},
    {label: 'Regionalverband Saarbrücken', dataset: 'counties', id: '10041'},
    {label: 'Merzig-Wadern', dataset: 'counties', id: '10042'},
    {label: 'Neunkirchen', dataset: 'counties', id: '10043'},
    {label: 'Saarlouis', dataset: 'counties', id: '10044'},
    {label: 'Saarpfalz-Kreis', dataset: 'counties', id: '10045'},
    {label: 'St. Wendel', dataset: 'counties', id: '10046'},
    {label: 'Berlin', dataset: 'counties', id: '11001'},
    {label: 'Brandenburg an der Havel', dataset: 'counties', id: '11002'},
    {label: 'Cottbus', dataset: 'counties', id: '11003'},
    {label: 'Frankfurt (Oder)', dataset: 'counties', id: '11004'},
    {label: 'Potsdam', dataset: 'counties', id: '11005'},
    {label: 'Barnim', dataset: 'counties', id: '11006'},
    {label: 'Dahme-Spreewald', dataset: 'counties', id: '11007'},
    {label: 'Elbe-Elster', dataset: 'counties', id: '11008'},
    {label: 'Havelland', dataset: 'counties', id: '11009'},
    {label: 'Märkisch-Oderland', dataset: 'counties', id: '11010'},
    {label: 'Oberhavel', dataset: 'counties', id: '11011'},
    {label: 'Oberspreewald-Lausitz', dataset: 'counties', id: '11012'},
    {label: 'Oder-Spree', dataset: 'counties', id: '12051'},
    {label: 'Ostprignitz-Ruppin', dataset: 'counties', id: '12052'},
    {label: 'Potsdam-Mittelmark', dataset: 'counties', id: '12053'},
    {label: 'Prignitz', dataset: 'counties', id: '12054'},
    {label: 'Spree-Neiße', dataset: 'counties', id: '12060'},
    {label: 'Teltow-Fläming', dataset: 'counties', id: '12061'},
    {label: 'Uckermark', dataset: 'counties', id: '12062'},
    {label: 'Rostock', dataset: 'counties', id: '12063'},
    {label: 'Schwerin', dataset: 'counties', id: '12064'},
    {label: 'Mecklenburgische Seenplatte', dataset: 'counties', id: '12065'},
    {label: 'Rostock', dataset: 'counties', id: '12066'},
    {label: 'Vorpommern-Rügen', dataset: 'counties', id: '12067'},
    {label: 'Nordwestmecklenburg', dataset: 'counties', id: '12068'},
    {label: 'Vorpommern-Greifswald', dataset: 'counties', id: '12069'},
    {label: 'Ludwigslust-Parchim', dataset: 'counties', id: '12070'},
    {label: 'Chemnitz', dataset: 'counties', id: '12071'},
    {label: 'Erzgebirgskreis', dataset: 'counties', id: '12072'},
    {label: 'Mittelsachsen', dataset: 'counties', id: '12073'},
    {label: 'Vogtlandkreis', dataset: 'counties', id: '13003'},
    {label: 'Zwickau', dataset: 'counties', id: '13004'},
    {label: 'Dresden', dataset: 'counties', id: '13071'},
    {label: 'Bautzen', dataset: 'counties', id: '13072'},
    {label: 'Görlitz', dataset: 'counties', id: '13073'},
    {label: 'Meißen', dataset: 'counties', id: '13074'},
    {label: 'Sächsische Schweiz-Osterzgebirge', dataset: 'counties', id: '13075'},
    {label: 'Leipzig', dataset: 'counties', id: '13076'},
    {label: 'Leipzig', dataset: 'counties', id: '14511'},
    {label: 'Nordsachsen', dataset: 'counties', id: '14521'},
    {label: 'Dessau-Roßlau', dataset: 'counties', id: '14522'},
    {label: 'Halle (Saale)', dataset: 'counties', id: '14523'},
    {label: 'Magdeburg', dataset: 'counties', id: '14524'},
    {label: 'Altmarkkreis Salzwedel', dataset: 'counties', id: '14612'},
    {label: 'Anhalt-Bitterfeld', dataset: 'counties', id: '14625'},
    {label: 'Börde', dataset: 'counties', id: '14626'},
    {label: 'Burgenlandkreis', dataset: 'counties', id: '14627'},
    {label: 'Harz', dataset: 'counties', id: '14628'},
    {label: 'Jerichower Land', dataset: 'counties', id: '14713'},
    {label: 'Mansfeld-Südharz', dataset: 'counties', id: '14729'},
    {label: 'Saalekreis', dataset: 'counties', id: '14730'},
    {label: 'Salzlandkreis', dataset: 'counties', id: '15001'},
    {label: 'Stendal', dataset: 'counties', id: '15002'},
    {label: 'Wittenberg', dataset: 'counties', id: '15003'},
    {label: 'Erfurt', dataset: 'counties', id: '15081'},
    {label: 'Gera', dataset: 'counties', id: '15082'},
    {label: 'Jena', dataset: 'counties', id: '15083'},
    {label: 'Suhl', dataset: 'counties', id: '15084'},
    {label: 'Weimar', dataset: 'counties', id: '15085'},
    {label: 'Eisenach', dataset: 'counties', id: '15086'},
    {label: 'Eichsfeld', dataset: 'counties', id: '15087'},
    {label: 'Nordhausen', dataset: 'counties', id: '15088'},
    {label: 'Wartburgkreis', dataset: 'counties', id: '15089'},
    {label: 'Unstrut-Hainich-Kreis', dataset: 'counties', id: '15090'},
    {label: 'Kyffhäuserkreis', dataset: 'counties', id: '15091'},
    {label: 'Schmalkalden-Meiningen', dataset: 'counties', id: '16051'},
    {label: 'Gotha', dataset: 'counties', id: '16052'},
    {label: 'Sömmerda', dataset: 'counties', id: '16053'},
    {label: 'Hildburghausen', dataset: 'counties', id: '16054'},
    {label: 'Ilm-Kreis', dataset: 'counties', id: '16055'},
    {label: 'Weimarer Land', dataset: 'counties', id: '16056'},
    {label: 'Sonneberg', dataset: 'counties', id: '16061'},
    {label: 'Saalfeld-Rudolstadt', dataset: 'counties', id: '16062'},
    {label: 'Saale-Holzland-Kreis', dataset: 'counties', id: '16063'},
    {label: 'Saale-Orla-Kreis', dataset: 'counties', id: '16064'},
    {label: 'Greiz', dataset: 'counties', id: '16065'},
    {label: 'Altenburger Land', dataset: 'counties', id: '16066'},
  ],
};

export default Regions;
