name: "Build Python Package"
description: "Build one of the MEmilio Python packages. Creates wheel as artifact."
inputs:
  package:
    description: "Package to build."
    required: true
runs:
  using: "composite"
  steps:    
    - name: Install dependencies
      shell: bash
      run: yum install ninja-build -qy
    - name: Make artifact dir
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        mkdir wheelhouse
    - name: Build Python Wheels
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
        /opt/python/cp311-cp311/bin/python setup.py bdist_wheel
        # Exclude memilio-generation, because its a pure python package, cmake is only used in the build process to retrieve data from cpp
        if [[ -f "CMakeLists.txt" ]] && [ "${{ inputs.package }}" != "generation" ]; then 
          # includes native dependencies in the wheel
          for whl in dist/*.whl; do auditwheel repair "$whl"; done
        else
          # no auditwheel necessary for pure python packages, so only copy the wheels to the same output directory 
          cp dist/*.whl wheelhouse
        fi
        cp -r wheelhouse ..
    - name: Upload Python Wheels
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels-${{ inputs.package }}
        path: pycode/wheelhouse

