name: "Build MSVC"
description: "Build memilio c++ library using MSVC on Windows. Creates artifact build-windows-msvc-$version-$config."
inputs:
  config:
    description: "Configuration to build (Release or Debug, see CMAKE_BUILD_TYPE)"
    required: true
    default: "Release"
  version:
    description: "Version of the compiler that is used (latest or min)."
    required: true
    default: "latest"
  optional-dependencies:
    description: "Build the library with optional dependencies (ON or OFF). If OFF, adds `-nodep` to the artifact name"
    required: false
    default: "ON"
runs:
  using: "composite"
  steps:
    - name: Install ninja
      shell: pwsh
      run: choco install -y ninja
    - name: Install hdf5
      shell: pwsh
      # the installation writes the library to C:\HDF5, avoiding version numbers past the download step 
      run: |
        if ("${{ inputs.optional-dependencies }}" -eq "ON") {
          Write-Output "Downloading HDF5 1.14.6";
          Invoke-WebRequest -Uri "https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.6/hdf5-1.14.6-win-vs2022_cl.zip" -OutFile "hdf5-outer.zip";
          Write-Output "Extract HDF5";
          7z x -y "hdf5-outer.zip" "-o.";                                       # hdf5 comes double zipped
          7z x -y "hdf5/hdf5-*-win64.zip" "-oC:\";
          Get-ChildItem -Path "C:\HDF5-*-win64" | Rename-Item -NewName "HDF5"   # rename to remove version from extracted directory
        }
    - name: Build
      shell: cmd /C call {0}
      run: |
        cd cpp
        mkdir build-win
        cd build-win
        if min==${{ inputs.version }} (
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        ) else (
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        )
        cmake --version
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DMEMILIO_USE_BUNDLED_JSONCPP=${{ inputs.optional-dependencies }} -DHDF5_USE_STATIC_LIBRARIES=ON -DHDF5_DIR="C:\HDF5" ..
        cmake --build . -- -j 4
    - name: Upload build binary files
      uses: actions/upload-artifact@v7
      with:
        #artifacts in one pipeline must have a different name, so options must add a suffix to the artifact name if different values are used in the same pipeline
        name: build-cpp-windows-msvc-${{ inputs.version }}-${{ inputs.config }}${{ inputs.optional-dependencies == 'OFF' && '-nodep' || ''}}
        path: cpp/build-win/bin
        retention-days: 1
