name: "SBML Compile and Run Test"
description: "Compile the SBML integrator, run it on a test example and compile the result."
inputs:
  artifact-pattern:
    description: "Name of the build artifact that contains the unit test binary, and coverage artifacts that will be uploaded."
    required: true
  optional-deps:
    description: "Optional dependencies of unit test binary (ON or OFF, default ON). If OFF, adds `-nodep` to the artifact name."
    required: false
    default: "ON"
runs:
  using: "composite"
  steps:
    - name: Download libsbml
      shell: bash
      run: gh run download --repo sbmlteam/libsbml --pattern "Ubuntu * stable*" --dir /libsbml
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq -y install gcc-13
        sudo apt-get -qq -y install g++-13
        sudo apt-get -qq update
    - name: Download built test directory
      uses: actions/download-artifact@v4
      with:
        name: build-cpp-linux-${{ inputs.artifact-pattern }}${{ inputs.optional-deps == 'OFF' && '-nodep' || ''}}
        path: cpp
    - name: extract build archive
      shell: bash
      run: |
        cd cpp
        tar -xzf build.tar.gz
    - name: Build SBML converter
      shell: bash
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DMEMILIO_ENABLE_IPOPT=ON -Dsbml_DIR=/libsbml/lib/cmake ..
        cmake --build . -j 4
    # - name: Run unit tests
    #   shell: bash
    #   # always run tests as cmake target coverage
    #   # does not return an error if a test fails
    #   run: |
    #     cd cpp/build/bin
    #     sudo chmod a+x memilio-test
    #     ./memilio-test  --gtest_output="xml:report.xml" --gtest_repeat=${{ inputs.num-repeat }}
    # - name: Compute code coverage
    #   shell: bash
    #   # compute code coverage
    #   run: |
    #     if [[ "${{ inputs.coverage }}" == "ON" ]]; then
    #       cd cpp/build
    #       cmake --build . --target coverage/fast
    #     fi
    # - name: Upload test report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-cpp-linux-report-${{ inputs.artifact-pattern }}${{ inputs.optional-deps == 'OFF' && '-nodep' || ''}}
    #     path: cpp/build/bin/report.xml
    #     if-no-files-found: error
    #     retention-days: 1
    # - name: Upload coverage reports
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-cpp-coverage-reports-${{ inputs.artifact-pattern }}${{ inputs.optional-deps == 'OFF' && '-nodep' || ''}}
    #     path: |
    #       cpp/build/coverage.info
    #       cpp/build/coverage
    #     # coverage is only calculated from latest gcc debug build
    #     if-no-files-found: ${{ inputs.coverage == 'OFF' && 'ignore' || 'error' }}
    #     retention-days: 1
