name: "Apple Build"
description: "Build the C++ library on MacOS. Produces artifact build-cpp-mac-appleclang-$version-$config."
inputs:
  config:
    description: "Configuration to build (Release or Debug, see CMAKE_BUILD_TYPE)"
    required: true
    default: "Release"
  version:
    description: "Version of the compiler to use (min or latest)."
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cmake -B cpp/build-mac/ -S cpp/ -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DMEMILIO_ENABLE_IPOPT=OFF -DMEMILIO_ENABLE_HDF5=OFF
        cmake --build cpp/build-mac/ -j$(sysctl -n hw.logicalcpu)
    - name: Upload build directory
      uses: actions/upload-artifact@v7
      with:
        #artifacts in one pipeline must have a different name, so options must add a suffix to the artifact name if different values are used in the same pipeline
        name: build-cpp-mac-appleclang-${{ inputs.version }}-${{ inputs.config }}
        path: cpp/build-mac/bin/
        retention-days: 1
