name: Build wheels 

on: [pull_request, release]

jobs:

  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pypa/cibuildwheel@v2.16

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # if: github.event_name == 'release' && github.event.action == 'published'
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v5
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        # To test uploads to TestPyPI, uncomment the following:
        with:
          skip-existing: true
          # password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository-url: https://test.pypi.org/legacy/