name: PyPI

on:
  release:
    types:
      - published
  ### Uncomment the "push:" together with the "repository-url:" field of action pypa/gh-action-pypi-publish
  ### to make a release to TestPyPI. Building this is rather expensive so do not merge this uncommented!
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  ### @Reviewer: MAKE SURE THE LINE ABOVE IS COMMENTED OUT BEFORE MERGE! ###

jobs:

  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-26]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Build Wheels"
        uses: pypa/cibuildwheel@v3.4.1
        with:
          package-dir: pycode/memilio-simulation

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: "Build Source Distribution"
      run:  |
        cd pycode/memilio-simulation
        pipx run build --sdist

    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v7
      with:
        name: cibw-sdist
        path: pycode/memilio-simulation/dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v7
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          ### To test uploads to TestPyPI in a PR, uncomment the following, as well as the "push:" line at the top:
          repository-url: https://test.pypi.org/legacy/
